### ISSUE TITLE
Interfaces to support

### ISSUE THREAD

**Issue by gerhardberger** [megajanlott/cbor-decoder#19]
It should be clear what sort of interfaces will our module will support (passing a string, a stream or a file as parameter etc).

- [ ] Explore binary data representations in Python
- [ ] Conclude supported interfaces

**Comment by viktb** [comment]
Read **binary** input from **stdin**:
```python
import sys
input_bytes = sys.stdin.buffer.read()  # or .read(n) to read n bytes
```

Read **binary** input from a **file**:
```python
with open('input.bin', 'rb') as f:
    input_bytes = f.read()  # or .read(n) to read n bytes
```

Read **hexadecimal** input from **stdin**:
```python
import binascii
import sys
input_hex = sys.stdin.read()  # or .read(2*n) to read n bytes
input_bytes = binascii.unhexlify(input_hex)
```

We can wrap these in a class that extends [`IOBase`](https://docs.python.org/2/library/io.html#i-o-base-classes) to hide the actual input source and provide a unified byte stream for the module to work with.

We can support all of these formats with ease (even their combinations if needed), by using command line switches to specify the input. E.g.:
```
--input=/path/to/input     defaults to stdin if not specified
--input-format=[bin|hex]   defaults to bin(ary)
--output=/path/to/output   defaults to stdout if not specified
```

**Comment by vincegellar** [comment]
**High level decode:**

- decoder's main class 2 decode(), and 2 decodeHex() functions. One for streams, one for byte arrays.
- parameter: [IOBase](https://docs.python.org/2/library/io.html#i-o-base-classes), or byte array

[IOBase](https://docs.python.org/2/library/io.html#i-o-base-classes) could be wrapped by class `CBORStream`, or in case of hexadecimal stream by `HexBinStream`, then by `CBORStream`.
A byte array will be wrapped by [BytesIO](https://docs.python.org/2/library/io.html#io.BytesIO), then by the classes mentioned above.

**Low level decode:**

Each major type should have their own decoder class, which has the same interface as the top level decoder, except decodeHex. The top level decoder only propagates binary streams. The decoder classes return the decoded value.

**Return value:**

Simple major type decoders (eg. Integer) return their value, which will then be used by complex major types and the top level decoder to construct a python structure representing the CBOR. This structure can be exported to JSON.
